name: Deploy

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App Version'
        required: true
        type: string

jobs:
  publish-android:
    runs-on: macos-latest
    environment: android

    steps:
      - name: Set Build Number
        run: echo "VERSION_NUMBER=$(500 + ${{ github.run_number }})" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Import keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "dragonfruit.keystore"
          fileDir: './DragonFruit.Six.Client.Maui'
          encodedString: ${{ secrets.KEYSTORE_CONTENTS }}

      - name: Import IAM Credentials
        run: echo $IAM_KEY > google-play-iam.json
        env:
          IAM_KEY: ${{ secrets.GCLOUD_IAM }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '11'

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Install Workloads
        run: dotnet workload restore

      - name: Authenticate NuGet Registry
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text https://nuget.pkg.github.com/dragonfruitnetwork/index.json

      - name: NuGet Restore
        run: |
          dotnet restore
          dotnet add DragonFruit.Six.Client.Maui package DragonFruit.Six.Client.Services

      - name: Publish
        run: dotnet publish -f net7.0-android -c Release -p:Version=${{ inputs.version }} -p:ApplicationVersion=$VERSION_NUMBER -p:ApplicationDisplayVersion=${{ inputs.version }} -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_SECRET }} -p:AndroidSigningKeyPass=${{ secrets.KEY_SECRET }} DragonFruit.Six.Client.Maui

      - name: Fastlane (Internal Deployment)
        run: fastlane internal version_name:${{ inputs.version }} version_code:$VERSION_NUMBER
        if: ${{ github.event_name == 'workflow_dispatch' }}