name: Publish NuGet Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NuGet Package Version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release -v normal -p:Version=${{ inputs.version }}

      - name: Pack
        run: dotnet pack DragonFruit.Six.Client/DragonFruit.Six.Client.csproj -c Release --include-symbols --no-build -v normal -o . -p:PackageVersion=${{ inputs.version }}

      - name: Publish
        run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_KEY }} --skip-duplicate -s https://nuget.pkg.github.com/dragonfruitnetwork/index.json